name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests with Maven
      run: |
        mvn -f backend/ \
          --batch-mode \
          -Dmaven.test.failure.ignore=true \
          -Dsurefire.reportFormat=xml \
          -Dsurefire.useFile=true \
          test

    - name: Build with Maven
      run: mvn -B package --file backend/pom.xml

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      if: always()  # always run even if previous steps fail
      with:
        name: Maven Tests
        path: backend/target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: false  # Set to false to avoid failing when no reports are found
